FROM tensorflow/tensorflow:2.1.1-gpu AS tf_build
WORKDIR /mlp
COPY ./mlp ./mlp
COPY requirements.txt ./
COPY version.py ./
COPY setup.py ./
COPY proto_gen.py ./
COPY README.md ./
RUN python3 -m pip install .
