FROM tensorflow/tensorflow:2.3.1-gpu AS tf_build
WORKDIR /mlp
COPY ./mlp ./mlp
COPY requirements.txt ./
COPY version.py ./
COPY setup.py ./
COPY proto_gen.py ./
COPY README.md ./
RUN apt-get update
RUN apt-get install python3-pip -y
RUN python3 -m pip install .
